name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/coverage-final.json
          flags: unittests
      - name: Publish
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          git remote set-url origin "https://$GH_USER:$GH_TOKEN@github.com/$GH_REPO.git"
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_NAME"
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm whoami
          yarn publish:ci
